console.log("///////////////////////");
console.log("|| Victory is Mine! ||");
console.log("\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\");
console.log("///////////////////////");
console.log("|| Victory is Mine! ||");
console.log("\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\");
console.log("///////////////////////");
console.log("|| Victory is Mine! ||");
console.log("\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\");
console.log("///////////////////////");
console.log("|| Victory is Mine! ||");
console.log("\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\");